default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: debug-statements
      - id: check-ast # Simply check whether the files parse as valid python
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-builtin-literals # Require literal syntax when initializing empty or zero Python builtin types
      - id: check-docstring-first # Check a common error of defining a docstring after code
      - id: check-merge-conflict # Check for files that contain merge conflict strings
      - id: check-yaml # Check yaml files
      - id: end-of-file-fixer # Ensure that a file is either empty, or ends with one newline
      - id: mixed-line-ending # Replace or checks mixed line ending
      - id: trailing-whitespace # This hook trims trailing whitespace
      - id: file-contents-sorter # Sort the lines in specified files
        files: .*requirements*\.txt$
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.5b0
    hooks:
      - id: black
        args:
          - --line-length=100
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        args:
          - --print-width=100
          - --prose-wrap=always
          - --tab-width=2
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=100
          - --max-cognitive-complexity=15
          - --ignore=E203,E266,E501,W503
        additional_dependencies:
          - pep8-naming
          - flake8-builtins
          - flake8-comprehensions
          - flake8-bugbear
          - flake8-pytest-style
          - flake8-cognitive-complexity
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.0.0
    hooks:
      - id: pydocstyle
        args:
          - --convention=google
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a3
    hooks:
      - id: pylint
