name: forecast_bcl
channels:
  #  - https://levinthal:paradox@conda.graylab.jhu.edu
  - conda-forge # for cudatoolkit
  - defaults
dependencies:
  - python=3.7
  - pip=20.0.2
  - pip:
      - -r requirements.txt
